on:
  push:
    paths-ignore:
      - .*ignore
      - "!.dockerignore"
      - README.md
      - CHANGELOG.md
      - .pre-commit-config.yaml

  release:
    types:
      - published

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Publish Image
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Get Image Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=edge,branch=main
            type=pep440,pattern={{version}}
            type=pep440,pattern=v{{version}}
            type=pep440,pattern={{major}}
            type=pep440,pattern=v{{major}}
            type=pep440,pattern={{major}}.{{minor}}
            type=pep440,pattern=v{{major}}.{{minor}}

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
