on:
  push:
    paths-ignore:
      - .*ignore
      - "!.dockerignore"
      - README.md
      - .pre-commit-config.yaml

  release:
    types:
      - published

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  standard:
    name: Publish Standard Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Get Standard Image Metadata
        id: meta-standard
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=edge,branch=main
            type=pep440,pattern={{version}}
            type=pep440,pattern=v{{version}}
            type=pep440,pattern={{major}}
            type=pep440,pattern=v{{major}}

      - name: Build and Push Standard Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta-standard.outputs.tags }}
          labels: ${{ steps.meta-standard.outputs.labels }}
          annotations: ${{ steps.meta-standard.outputs.annotations }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  no-redis:
    name: Publish Redis-less Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Get Standard Image Metadata
        id: meta-standard
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=edge,branch=main,suffix=-no-redis
            type=pep440,pattern={{version}}-no-redis
            type=pep440,pattern=v{{version}}-no-redis
            type=pep440,pattern={{major}}-no-redis
            type=pep440,pattern=v{{major}}-no-redis

      - name: Build and Push Redis-less Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta-standard.outputs.tags }}
          labels: ${{ steps.meta-standard.outputs.labels }}
          annotations: ${{ steps.meta-standard.outputs.annotations }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

